POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Decoração",
    "description": "Escolha a decoração para sua festa, e nós a montamos.",
    "price": 1400,
    "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/68669be30425deca0c34668d

###
DELETE http://localhost:3000/api/services/68669be30425deca0c34668d

###
PUT http://localhost:3000/api/services/6866a5dd869ebb1b51833c86
Content-Type: application/json

{
    "name": "TESTE ATUALIZAÇÃO",
    "description": "Descrição do serviço",
    "price": 2500,
    "image": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Meu Evento 2",
    "author": "Rafaela",
    "description": "Festa de formatura animada",
    "budget": 9000,
    "image": "https://images.unsplash.com/photo-1607647074969-cc58ec404eb2?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "services": [
    {
        "name": "Um serviço X",
        "description": "Descrição do serviço",
        "price": 3500,
        "image": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        "name": "Um serviço y",
        "description": "Descrição do serviço",
        "price": 5500,
        "image": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    }
    ]
}

###
GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/6866ac5bdc37f01de474f407

###
DELETE http://localhost:3000/api/parties/6866ac5bdc37f01de474f407

###
PUT http://localhost:3000/api/parties/6866ad25dc37f01de474f409
Content-Type: application/json

{
    "title": "Meu Evento 2",
    "author": "Rafaela",
    "description": "Festa de formatura animada",
    "budget": 11000,
    "image": "https://images.unsplash.com/photo-1607647074969-cc58ec404eb2?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "services": [
    {
        "name": "Um serviço X",
        "description": "Descrição do serviço",
        "price": 3500,
        "image": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        "name": "Um serviço y",
        "description": "Descrição do serviço",
        "price": 6500,
        "image": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    }
    ]
}